export const ActionTypes = {
    LOGIN_STATUS : 'LOGIN_STATUS',
    LOGIN_STATUS_SET : 'LOGIN_STATUS_SET',
    LOGIN_STATUS_GET : 'LOGIN_STATUS_GET',
    SINGLE_USER_DATA : 'SINGLE_USER_DATA',
    SINGLE_USER_SET_DATA : 'SINGLE_USER_SET_DATA',
    SINGLE_USER_GET_DATA : 'SINGLE_USER_GET_DATA',
    FETCH_USERS_DATA : "FETCH_USERS_DATA",
    ERROR_FETCH_USERS_DATA : "ERROR_FETCH_USERS_DATA",
    FETCH_AIRLINES_DATA : "FETCH_AIRLINES_DATA",
    BOOK_TICKET_STATUS : 'BOOK_TICKET_STATUS',
    BOOK_TICKET_STATUS_SET : 'BOOK_TICKET_STATUS_SET',
    BOOK_TICKET_STATUS_GET : 'BOOK_TICKET_STATUS_GET',
    BOOK_TICKET_DETAILS : 'BOOK_TICKET_DETAILS'
};