export const ActionTypes = {
    LOGIN_STATUS : 'LOGIN_STATUS',
    SINGLE_USER_DATA : 'SINGLE_USER_DATA',
    FETCH_USERS_DATA : "FETCH_USERS_DATA",
    ERROR_FETCH_USERS_DATA : "ERROR_FETCH_USERS_DATA",
    FETCH_AIRLINES_DATA : "FETCH_AIRLINES_DATA",
    BOOK_TICKET_STATUS : 'BOOK_TICKET_STATUS',
    BOOK_TICKET_DETAILS : 'BOOK_TICKET_DETAILS'
};